### ISSUE TITLE
The naming of the component tab for this project is inconsistent with others

### ISSUE THREAD

**Issue by peardox** [Embarcadero/PythonPackages4Delphi#1]
Everything else is Python [[ - ] Subproject]

This one therefore looks 'wrong' - there's nothing actually wrong of course (I must have a bit of OCD I wasn't aware of)

Look...

![pp4d](https://user-images.githubusercontent.com/1549219/195406381-5c5ea226-9163-4b8e-b5c8-a673bb5be6f1.png)

**Comment by lmbelo** [comment]
Let's figure out a good name. Any suggestion?

**Comment by peardox** [comment]
Python - Extra Packages?

The Dash is what really bothers me :)

**Comment by peardox** [comment]
The location of lib and images also appears to be 'floating' - these should really be consistant - personally I prefer src to ONLY contain source with lib and images being off project root

See https://github.com/Embarcadero/P4D-Data-Sciences/issues/23

I'm currently writing a little Wizard - it was either write the six components I need or write a Wizard, Wizard is a better bet so doing that. ATM I don't quite know where I should put lib and images is both in src and root in this package. I think I'll go for an off-root structure unless anyone has a good reason not to.

**Comment by peardox** [comment]
Can't assign myself - well, done it

**Comment by lmbelo** [comment]
What is all these .drpoj modifications? It is not supposed to be changed.

**Comment by Priyatham10** [comment]
I can think of a name. Say, `Python - PIP Packages for Delphi`. This solves the consistency of naming convention with `-` after Python like others and also saying these are PIP packages provided as components for direct use.

**Comment by lmbelo** [comment]
@Priyatham10 these are not PIP only intended packages.

**Comment by peardox** [comment]
Did all my Linux Activations just get wiped?

**Comment by lmbelo** [comment]
There were too many modifications in a single commit. Try to break it down into smaller commits and splitted pull requests. It gets much easier to review.

**Comment by peardox** [comment]
Moving lib back to the root involves very small changes to a lot of files and they have to all be done or none done.

There are two files that need changes per component : src/Component/P4DComponent.dproj + src/Component/dclP4DComponent.dproj - this repo has 7 components so 14 files need altering for everything to move back to /lib

Renaming the palette page has to be done for each ComponentReg.pas - again, all or nothing

When Jim moved everything around there would have been a lot more changes that this PR

The only alternative would be individual PRs for each component but no individual PR would produce one lib and one palette

**Comment by peardox** [comment]
Oh, enabling Linux will also have changed a lot of files... 29 at a guess

**Comment by lmbelo** [comment]
I understand. As you changed it, other settings were changed as well.

**Comment by peardox** [comment]
I can write you a step-by-step what to change - it's probably quicker than a huge PR for both of us :)

The actual changes are really simple (took me a few hours to work them all out though)

**Comment by lmbelo** [comment]
Yes, sure. Describe it here and I will do it right away.
